/**
*Copyright 2009, Mohit Gvalani

*This file is part of CGVRS.
*CGVRS is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
*CGVRS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
*You should have received a copy of the GNU General Public License along with CGVRS.  If not, see <http://www.gnu.org/licenses/>.
*/


#include<graphics.h>
#include<dos.h>
#include<math.h>
#include<iostream.h>
#include<conio.h>

/*void main()
{
	int gd = DETECT,gm;
	initgraph(&gd,&gm,"");

	int i = 360;
	int sangle = 10, eangle = 0,radius = 300;
	do
	{       sangle+=10;
		eangle+=10;
		i--;
		//if(i==0)
		//{
			radius-=1;
			//i=360;
		//}

		delay(30);
		arc(getmaxx()/2,getmaxy()/2,eangle,sangle,radius);
	}while(radius!=0);
	getch();

	//arc(100,100,990,1000,10);
	//getch();

}*/
