#include<graphics.h>
#include<dos.h>
#include<math.h>
#include<iostream.h>
#include<conio.h>

/*void main()
{
	int gd = DETECT,gm;
	initgraph(&gd,&gm,"");

	int i = 360;
	int sangle = 10, eangle = 0,radius = 300;
	do
	{       sangle+=10;
		eangle+=10;
		i--;
		//if(i==0)
		//{
			radius-=1;
			//i=360;
		//}

		delay(30);
		arc(getmaxx()/2,getmaxy()/2,eangle,sangle,radius);
	}while(radius!=0);
	getch();

	//arc(100,100,990,1000,10);
	//getch();

}*/
